### ISSUE TITLE
Event Streams- Broker component not available in namespace.

### ISSUE THREAD

**Issue by egargaritano** [IBM/event-streams#17] opened 2019-02-01 15:53 UTC
## Issue Description

After installing IBM Cloud Private-CE 3.1.1 with 1 master and 3 worker nodes on RHEL 7 operating system, I installed the Eventstreams-dev HELM release 1.1.0 on a new namespace.  Then launched the Event Streams UI.  The UI was showing that 1 component is not available, which turned out to the the 3 brokers. All other components were enabled. Can't proceed with testing until this component is available.  

Further investigation using the kubectl commands showed that only 2/4 containers are starting in es-kafka-0, es-kafka-1 and es-kafka-2 brokers.  

I have attached the logs for your further investigation. Please help.

Thanks,
Edwin

[describepod_kafka-sts-0.txt](https://github.com/IBM/event-streams/files/2822274/describepod_kafka-sts-0.txt)
[describepod_kafka-sts-1.txt](https://github.com/IBM/event-streams/files/2822275/describepod_kafka-sts-1.txt)
[describepod_kafka-sts-2.txt](https://github.com/IBM/event-streams/files/2822276/describepod_kafka-sts-2.txt)
[getnodes.txt](https://github.com/IBM/event-streams/files/2822277/getnodes.txt)
[getpods.txt](https://github.com/IBM/event-streams/files/2822278/getpods.txt)
[logs_kafka-sts-0_container_healthcheck.txt](https://github.com/IBM/event-streams/files/2822279/logs_kafka-sts-0_container_healthcheck.txt)
[logs_kafka-sts-0_container_kafka.txt](https://github.com/IBM/event-streams/files/2822280/logs_kafka-sts-0_container_kafka.txt)
[logs_kafka-sts-0_container_metrics-proxy.txt](https://github.com/IBM/event-streams/files/2822281/logs_kafka-sts-0_container_metrics-proxy.txt)
[logs_kafka-sts-0_container_metrics-reporter.txt](https://github.com/IBM/event-streams/files/2822282/logs_kafka-sts-0_container_metrics-reporter.txt)

* Describe the problem
* Describe the application flow or what steps were being taken when the problem occurred
* If the issue is reproducible provide a set of instructions describing how to reproduce it, including screenshots if they might assist
* Include any error messages, stack traces and logs associated with the error, in full, in text format (ie not a screenshot)
* Describe the expected behaviour
* Did this used to work? If so what has changed, for example was any maintenance of the system performed?

## Environment

* IBM Event Streams Version:
* IBM Cloud Private (ICP) Version:
* Operating system of ICP install: 
* Browser (for UI issues):

**Comment by EmmaHumber** [comment] 2019-02-03 22:08
Hi Edwin

Thanks for getting in touch.  From the logs you've sent in it looks like this Kafka pod can't talk to at least one of the Zookeepers instances, however the logs show that the three Zookeeper pods are up and running.

I can't tell from the information above why this might be.  Could you run the script at  

https://github.com/IBM/charts/blob/master/stable/ibm-eventstreams-dev/additionalFiles/get-logs.sh

and attach the file generated to this issue please?

Are you running SE Linux, or standard Red Hat?  

Can you ping one worker node from the other worker nodes?  eg ssh into 10.69.5.67 and see if you can ping 10.69.5.68 and 10.69.5.69.

Can you exec into the Kafka container:
`kubectl exec -it KAFKA_POD_NAME -c kafka bash`

and see if it can contact the zookeeper containers.  There's no ping, so try nc:

`nc -z 172.18.167.193 2181`
`nc -z 172.18.186.106 2181`

Note that I can't work out the ip of the third zookeeper from the Kafka healthcheck logs - I'm assuming the Kafka healthcheck can communicate with this ZK, possibly because it is on the same node as the Kafka pod the logs above are from.  

Thanks
Emma

**Comment by egargaritano** [comment] 2019-02-05 01:16
Hi Emma,

 

Thanks for your email.  I ran the script but I was going nowhere as I was getting an error as follows:

 

[root@onthord0bav001 ~]# . get-logs.sh

-bash: $'\r': command not found

-bash: $'\r': command not found

-bash: $'\r': command not found

-bash: $'\r': command not found

': not a valid identifier

': not a valid identifier

-bash: $'\r': command not found

-bash: $'\r': command not found

-bash: get-logs.sh: line 45: syntax error near unexpected token `$'in\r''

'bash: get-logs.sh: line 45: `    case $1 in

 

The system is based on RHEL 7 and is running Selinux (enforcing mode).

All nodes can ping each other (that is .67 can ping .68 and .69; .68 can ping .67 and .69; and .69 can ping .67 and .68)

 

The first two zookeeper nodes cannot be contacted (see nc_results.txt attached).  You are right about the 3rd zookeeper that it can be contacted because it probably resides on the same node.

 

Let me know if you need more tests to be performed.

 

Thanks,

Edwin

**Comment by EmmaHumber** [comment] 2019-02-05 07:31
Hi Edwin - did you save the script on a Windows machine first?  It looks like there are carriage return ("/r") characters on the end of each line which Linux won't be happy with.

My suspicion is that there is a setting in the SELinux configuration that is preventing the pods from talking across nodes.  Can you also attach your SELinux settings from /etc/selinux/config

Is it possible for you to test with SELinux disabled to see if this resolves the problem?  That will either rule SELinux configuration out, or highlight where to focus investigation.

Thanks
Emma

**Comment by egargaritano** [comment] 2019-02-05 17:25
Part 2 of the logs.

 

Thx,
Edwin

**Comment by EmmaHumber** [comment] 2019-02-05 17:37
Hi Edwin - I can't see any new logs attached to this issue.  Could you double check you added them as it looks like reply via email might not be including files.

Thanks
Emma

**Comment by egargaritano** [comment] 2019-02-05 17:39
Part1a didn’t go through, so I split into 3 parts.  See attached.

 

Thx,
Edwin

**Comment by egargaritano** [comment] 2019-02-05 17:40
Part1b

**Comment by egargaritano** [comment] 2019-02-05 17:40
Part 1c

**Comment by EmmaHumber** [comment] 2019-02-05 18:12
Hi - thanks for attempting to upload the docs again.  Can you see the attachments on this issue?  I can't see them unfortunately.  I was wondering if you could try using the git web client to upload the files rather than email.

How did you get on with disabling SELinux to exclude this from what's going on?

Regards
Emma

**Comment by egargaritano** [comment] 2019-02-05 19:22
Hi Emma,

 

I split the logs into four parts.  Were you able to see them?

I disabled Selinux by running the command – setenforce 0.

 

Let me know if you still want me to upload the log files.

 

Thanks,
Edwin

**Comment by egargaritano** [comment] 2019-02-05 19:57
Just uploaded the entire logs via the Git Client.  Can you see them now?

 

Thx,
Edwin

 

From: egargaritano <egargaritano@gmail.com> 
Sent: Tuesday, February 5, 2019 2:22 PM
To: 'IBM/event-streams' <reply@reply.github.com>; 'IBM/event-streams' <event-streams@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [IBM/event-streams] Event Streams- Broker component not available in namespace. (#17)

 

Hi Emma,

 

I split the logs into four parts.  Were you able to see them?

I disabled Selinux by running the command – setenforce 0.

 

Let me know if you still want me to upload the log files.

 

Thanks,
Edwin

**Comment by egargaritano** [comment] 2019-02-06 11:48
Hi Emma,

 

I uploaded the logs in its entirety via the Git Client.  I disabled the Selinux one each node using the setenforce 0 command and all nodes are showing permissive mode now.

 

Hope this helps.

 

Thanks,
Edwin

**Comment by EmmaHumber** [comment] 2019-02-06 13:20
[test.log](https://github.com/IBM/event-streams/files/2836464/test.log)

Test log above

**Comment by andrewdunnings** [comment] 2019-02-06 15:39
Hi Edwin,

I'm replying on behalf of Emma:

Did disabling SELinux have any affect on the state of the Event Streams install, for example is the UI showing the brokers as unavailable still?   If there’s no difference in behavior could you
1) confirm se linux is disabled by running sestatus and checking the output, then
2) run kubectl delete pod ZOOKEEPER_POD_NAME for each zookeeper in turn, followed by a kubectl delete pod KAFKA_POD_NAME for each kafka in turn, waiting for each pod to restart before deleting the next, then
3) run kubectl get pods to confirm the status of each pod

If the pods still don’t all come up, we can remove the event streams network policy next:

Save the network policy files for kafka and zookeeper:
1. `kubectl get netpol -o yaml $(kubectl get netpol | grep zookeeper | awk '{ print $1 }') > zookeeper-netpol.yaml`
2. `kubectl get netpol -o yaml $(kubectl get netpol | grep kafka | awk '{ print $1 }') > kafka-netpol.yaml`

Delete the network policies for kafka and zookeeper:
3. `kubectl delete netpol $(kubectl get netpol | grep zookeeper | awk '{ print $1 }')`
4. `kubectl delete netpol $(kubectl get netpol | grep kafka | awk '{ print $1 }')`

5. Restart the zookeeper and kafka pods as described above
6. Run `kubectl get pods` to see status

Recreate the network policies for kafka and zookeeper:
1. `kubectl apply -f zookeeper-netpol.yaml`
2. `kubectl apply -f kafka-netpol.yaml`


I’m wondering if there is some issue attaching large files to this issue as I still can’t see them linked, so I’m going to suggest another route to supply the logs


https://slack-invite-ibm-cloud-tech.mybluemix.net/ - fill in your email to request an invite to join our slack workspace.

Once the invite has come through go to the channel https://ibm-cloud-tech.slack.com/messages/CADFRM4FR/ and post in there referencing this issue.  You should be able to upload the log file there.

Thanks
Andrew

**Comment by egargaritano** [comment] 2019-02-08 04:09
Hi Andrew,

 

Selinux is disabled, it’s in permissive mode now (ran the setenforce 0 command). 

I performed the commands to stop/start pods, then delete network policies.

After network policies were deleted, all pods came up.  When I reapplied the policies, there was an error “Error from server (Conflict): Operation cannot be fulfilled on networkpolicies.extensions "kafka-ibm-es-zookeeper-access": the object has been modified; please apply your changes to the latest version and try again”



 

Not sure what this error is.  Does it wait for my input?  It shows system is healthy though.  I then deleted the nework policies again, and this error is gone.

 

Any thoughts?

 

Thanks for your help.

 

Regards,

Edwin

**Comment by andrewdunnings** [comment] 2019-02-08 11:58
Hi Edwin,

It's a good sign that the containers are coming up without the network policies in place.

The purpose of the network policies is to enforce restrictions on which pods can communicate with each other on particular ports. For example: the Kafka network policy has a rule that allows Kafka to send traffic to port 2181 of the Zookeeper pod, and similarly the Zookeeper network policy has a rule which allows it to receive traffic from the Kafka pod on port 2181.
These rules are put in place to prevent communication between pods that aren't designed to talk to each other, for security reasons.

It looks like the problem you are experiencing is that the network policies for Kafka and Zookeeper are incorrectly preventing them from communicating, since when you deleted the network policies all of the containers came up. This is unexpected behaviour so I'd like to investigate why this is occurring.

Please could you send the following:
- Output of a `kubectl get netpol` command
- The `zookeeper-netpol.yaml` and `kafka-netpol.yaml` files 
- The output of a `kubectl describe pod ZOOKEEPER_POD` and `kubectl describe pod KAFKA_POD` of one of each of the new pods

In the short term, you can make a decision whether you are happy to run without the Zookeeper and Kafka network policies in place. The consequence of this would be that the Kafka and Zookeeper pods will be able to contacted by other pods within your cluster.

Thanks,
Andrew

**Comment by egargaritano** [comment] 2019-02-08 18:41
Hi Andrew,

 

Here are the results of your request.  See attached.

I’m happy to run without policies for now so we can just test the functionality.  Over time, we would want to enforce security as we might be deploying various kafka namespaces for each environment.

 

Let me know if you have found anything that could be the root cause.

 

Thanks,
Edwin

**Comment by EmmaHumber** [comment] 2019-02-08 23:07
Hi Edwin

Thanks for the output of the kafka and zookeeper kubectl describe pods commands

Could you also supply the contents of the two .yaml files used to save the network policy information, ie zookeeper-netpol.yaml and kafkan-netpol.yaml

It looks like something has gone awry with the network policy and we'll need these two files to start to understand what that might be.

Thank you!
Emma

**Comment by egargaritano** [comment] 2019-02-11 15:29
Thanks Emma.  Please see attached yaml files.

 

Regards,

Edwin

**Comment by EmmaHumber** [comment] 2019-02-11 17:26
HI @egargaritano There's still something odd about how files get attached to this issue and I can't see them.

Could you copy and paste the text of the two network policy output files into the email response directly as you did for the kubectl describe commands above, as that way I can see the content.

Thanks
Emma

**Comment by egargaritano** [comment] 2019-02-11 19:54
Hi Emma,

 

See below.

 

Thanks,
Edwin

 

 

 

KAFKA-NETPOL.YAML

 

apiVersion: v1

items:

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: essential

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-access-default-deny

    namespace: thor-namespace

    resourceVersion: "654803"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-access-default-deny

    uid: fe14d612-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 53

        protocol: UDP

      - port: 53

        protocol: TCP

    podSelector:

      matchLabels:

        release: kafka

    policyTypes:

    - Ingress

    - Egress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: essential

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-access-jobs

    namespace: thor-namespace

    resourceVersion: "654814"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-access-jobs

    uid: fe18dd8b-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    podSelector:

      matchLabels:

        component: essential

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: elastic

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-elastic-access

    namespace: thor-namespace

    resourceVersion: "654806"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-elastic-access

    uid: fe161849-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 9080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: indexmgr

    - ports:

      - port: 9300

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: elastic

    ingress:

    - from:

      - podSelector:

          matchLabels:

            component: indexmgr

      ports:

      - port: 9200

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: elastic

      ports:

      - port: 9300

        protocol: TCP

    podSelector:

      matchLabels:

        component: elastic

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: indexmgr

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-indexmgr-access

    namespace: thor-namespace

    resourceVersion: "654811"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-indexmgr-access

    uid: fe17ae7b-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 9200

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: elastic

    - ports:

      - port: 9080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: rest

    ingress:

    - from:

      - podSelector:

          matchLabels:

            component: kafka

      ports:

      - port: 8080

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: elastic

      - podSelector:

          matchLabels:

            component: rest

      ports:

      - port: 9080

        protocol: TCP

    podSelector:

      matchLabels:

        component: indexmgr

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: kafka

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-kafka-access

    namespace: thor-namespace

    resourceVersion: "654819"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-kafka-access

    uid: fe1a1d43-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    - ports:

      - port: 2181

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: zookeeper

    - ports:

      - port: 9092

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: kafka

    - ports:

      - port: 8080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: indexmgr

    - ports:

      - port: 8443

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: security

    ingress:

    - from:

      - podSelector:

          matchLabels:

            component: rest

      ports:

      - port: 8084

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: proxy

      ports:

      - port: 8093

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: kafka

      ports:

      - port: 9092

        protocol: TCP

    - ports:

      - port: 8081

        protocol: TCP

    podSelector:

      matchLabels:

        component: kafka

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: proxy

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-proxy-access

    namespace: thor-namespace

    resourceVersion: "654825"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-proxy-access

    uid: fe1b37d8-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    - ports:

      - port: 8093

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: kafka

    - ports:

      - port: 9080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: rest

    ingress:

    - {}

    podSelector:

      matchLabels:

        component: proxy

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: rest

      component: rest

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-rest-access

    namespace: thor-namespace

    resourceVersion: "654792"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-rest-access

    uid: fe0e82a9-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    - ports:

      - port: 8084

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: kafka

    - ports:

      - port: 9080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: indexmgr

    - ports:

      - port: 2181

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: zookeeper

    - ports:

      - port: 8443

        protocol: TCP

    - ports:

      - protocol: TCP

      - port: 53

        protocol: UDP

    ingress:

    - {}

    podSelector:

      matchLabels:

        component: rest

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ibm-eventstreams-dev

      component: security

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-security-access

    namespace: thor-namespace

    resourceVersion: "654826"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-security-access

    uid: fe207465-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8443

        protocol: TCP

    ingress:

    - from:

      - podSelector:

          matchLabels:

            component: kafka

      - podSelector:

          matchLabels:

            component: rest

      - podSelector:

          matchLabels:

            component: ui

      ports:

      - port: 8443

        protocol: TCP

    podSelector:

      matchLabels:

        component: security

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: ui

      component: ui

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-ui-access

    namespace: thor-namespace

    resourceVersion: "654794"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-ui-access

    uid: fe1164f4-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    - ports:

      - port: 9080

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: rest

    - ports:

      - port: 8443

        protocol: TCP

    - ports:

      - port: 8443

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: security

    - ports:

      - port: 4300

        protocol: TCP

    ingress:

    - {}

    podSelector:

      matchLabels:

        component: ui

        release: kafka

    policyTypes:

    - Egress

    - Ingress

- apiVersion: extensions/v1beta1

  kind: NetworkPolicy

  metadata:

    creationTimestamp: 2019-01-30T17:17:59Z

    generation: 1

    labels:

      app: ibm-es

      chart: zookeeper

      component: zookeeper

      heritage: Tiller

      release: kafka

    name: kafka-ibm-es-zookeeper-access

    namespace: thor-namespace

    resourceVersion: "654799"

    selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-zookeeper-access

    uid: fe12ceca-24b2-11e9-9eb1-00505692608c

  spec:

    egress:

    - ports:

      - port: 8001

        protocol: TCP

    - ports:

      - port: 2888

        protocol: TCP

      - port: 3888

        protocol: TCP

      to:

      - podSelector:

          matchLabels:

            component: zookeeper

    ingress:

    - from:

      - podSelector:

          matchLabels:

            component: kafka

      - podSelector:

          matchLabels:

            component: rest

      ports:

      - port: 2181

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: zookeeper

      ports:

      - port: 2888

        protocol: TCP

    - from:

      - podSelector:

          matchLabels:

            component: zookeeper

      ports:

      - port: 3888

        protocol: TCP

    podSelector:

      matchLabels:

        component: zookeeper

        release: kafka

    policyTypes:

    - Egress

    - Ingress

kind: List

metadata:

  resourceVersion: ""

  selfLink: ""

 

 

ZOOKEEPER-NETPOL.YAML

 

apiVersion: extensions/v1beta1

kind: NetworkPolicy

metadata:

  creationTimestamp: 2019-01-30T17:17:59Z

  generation: 1

  labels:

    app: ibm-es

    chart: zookeeper

    component: zookeeper

    heritage: Tiller

    release: kafka

  name: kafka-ibm-es-zookeeper-access

  namespace: thor-namespace

  resourceVersion: "654799"

  selfLink: /apis/extensions/v1beta1/namespaces/thor-namespace/networkpolicies/kafka-ibm-es-zookeeper-access

  uid: fe12ceca-24b2-11e9-9eb1-00505692608c

spec:

  egress:

  - ports:

    - port: 8001

      protocol: TCP

  - ports:

    - port: 2888

      protocol: TCP

    - port: 3888

      protocol: TCP

    to:

    - podSelector:

        matchLabels:

          component: zookeeper

  ingress:

  - from:

    - podSelector:

        matchLabels:

          component: kafka

    - podSelector:

        matchLabels:

          component: rest

    ports:

    - port: 2181

      protocol: TCP

  - from:

    - podSelector:

        matchLabels:

          component: zookeeper

    ports:

    - port: 2888

      protocol: TCP

  - from:

    - podSelector:

        matchLabels:

          component: zookeeper

    ports:

    - port: 3888

      protocol: TCP

  podSelector:

    matchLabels:

      component: zookeeper

      release: kafka

  policyTypes:

  - Egress

  - Ingress

**Comment by EmmaHumber** [comment] 2019-02-12 15:19
Hi @egargaritano 

The network policies for Kafka, Zookeeper and the deny policy match my working system, the ports look correct, as do the container names and policy labels.


So, let's start back at the beginning.

1) Disable SE Linux
2) Install a fresh Event Streams with a new release name
3) Check the pods all come up

Let me know how you get on.

Thanks
Emma

**Comment by egargaritano** [comment] 2019-02-13 13:24
Thanks Emma.

 

I opened a PMR ticket to help out on the ICP part and they have recommended to uninstall the ICP-CE version and install the ICP-EE version instead.  Also will reinstall the EventStreams after that as you suggested.  I will keep you up-to-date as to the status of this.  Thanks for all your help.

 

Regards,

Edwin

**Comment by EmmaHumber** [comment] 2019-02-22 15:55
Hi Edwin, 

From the PMR ticket I saw I think you're up and running.

I'm closing this off for now, please do reopen if you have any further issues.

Thanks
Emma

**Closed by EmmaHumber** 2019-02-22 15:55 UTC
