### ISSUE TITLE
Metrics proxy restarting due to an index out of bounds panic error

### ISSUE THREAD

**Issue by tagarr** [IBM/event-streams#53] opened 2020-01-27 15:12 UTC
The metrics proxy is continuously recycling with index out of Bounds on compressUpdate

panic: runtime error: index out of range

goroutine 2580 [running]:
github.ibm.com/mhub/qp-kafka-metrics-proxy/connector.(*ESearch).compressUpdate(0xc0001ee000, 0x5e26c6c6, 0xc0003d3090, 0xc000671620, 0xc0001e0400)
	/home/jenkins/go/src/github.ibm.com/mhub/qp-kafka-metrics-proxy/connector/compresssearch.go:157 +0xf8f
github.ibm.com/mhub/qp-kafka-metrics-proxy/connector.(*ESearch).compressRecords(0xc0001ee000, 0xc0002cc000, 0xfe)
	/home/jenkins/go/src/github.ibm.com/mhub/qp-kafka-metrics-proxy/connector/compresssearch.go:113 +0x2af
github.ibm.com/mhub/qp-kafka-metrics-proxy/connector.(*ESearch).waitForEvents.func1(0xc0001ee000, 0xc0002cc000, 0xfe, 0x5e26c6c5)
	/home/jenkins/go/src/github.ibm.com/mhub/qp-kafka-metrics-proxy/connector/esearch.go:186 +0x3f
created by github.ibm.com/mhub/qp-kafka-metrics-proxy/connector.(*ESearch).waitForEvents
	/home/jenkins/go/src/github.ibm.com/mhub/qp-kafka-metrics-proxy/connector/esearch.go:185 +0x6e2

**Comment by nictownsend** [comment] 2020-07-14 13:26
Internal issue: 4723

Fixed in: 2019.4.2

**Closed by nictownsend** 2020-07-14 13:26 UTC

**Comment by nictownsend** [comment] 2020-07-15 09:27
Workaround:

The issue is occurring when Event Streams is indexing the messages - the resulting index is used to power the message browser in the Event Streams UI. 

Perform a helm upgrade to disable `message indexing` - the impact being that the message browser UI will not show the histogram of message activity in the topic.
